/* ---- Vorschläge: bekannte Standard-Executes als Startpunkt ---- */
const PRESETS = {
de_dust2:[
 {name:"A Split – Long & Catwalk",side:"T",tags:["Execute","A"],
  roles:["Entry Long","Support Long","Catwalk","Mid / Info","Lurk B-Tunnels"],
  steps:["Flash über Long Doors, Doors aufmachen, Long Corner smoken.","Cat-Spieler nimmt Short mit Flash von Mid, hält Info auf Kurz.","CT smoken, Goose/Barrels mollen, dann Entry über Doors.","Cat schwingt zeitgleich rein, Trades auf Ninja und Platform.","Post-Plant: Long Corner + Goose, Lurk hält Tunnels."],
  util:[["smoke","Long Corner"],["smoke","CT-Spawn"],["flash","Pop-Flash über Doors"],["molo","Goose / Barrels"],["flash","Cat-Flash von Mid"]]},
 {name:"B Rush – Upper Tunnels",side:"T",tags:["Rush","B"],
  roles:["Entry B-Doors","Trade","Molly-Support","Flash-Support","Mid-Fake / Lurk"],
  steps:["Ein Spieler wirft Mid-Flash und schießt kurz Mid an (Fake).","4 sammeln in Upper Tunnels, Window smoken.","Molly auf Back Plat, Flash rein, alle vier auf einmal raus.","Site aufteilen: Car, Back Plat, Doors.","Post-Plant: Tunnels-Seite halten, Lurk rotiert über Mid."],
  util:[["smoke","B-Window"],["molo","Back Plat / Closet"],["flash","Entry-Flash B-Doors"],["flash","Mid-Fake Flash"]]},
 {name:"Mid Control → B Split",side:"T",tags:["Split","B","Mid"],
  roles:["AWP Mid","Xbox-Support","Doors-Entry","Tunnels 1","Tunnels 2"],
  steps:["Xbox und CT smoken, Mid-Kontrolle aufbauen.","Doors öffnen, Info sammeln, kein Overpeek.","Zwei nehmen Upper Tunnels, warten auf Call.","Auf Call: Window-Smoke + Flash, Doors und Tunnels gleichzeitig.","Cross-Fire auf Site, Post-Plant von beiden Seiten."],
  util:[["smoke","Xbox"],["smoke","CT-Spawn"],["smoke","B-Window"],["flash","Doors-Entry"],["molo","Back Plat"]]},
 {name:"Standard 2-1-2",side:"CT",tags:["Default","Setup"],
  roles:["A Long","A Site / Ninja","Mid AWP","B Doors","B Back Plat"],
  steps:["Long-Spieler hält passiv hinter Blue, kein Free-Peek.","Mid-AWP hält Doors, fällt bei Druck auf Xbox zurück.","B-Doors nimmt Tunnels-Timing mit Molly früh.","Bei A-Push: Mid rotiert über CT, B hält alleine bis Info.","Retakes immer mit Smoke + Flash, nie ohne Util."],
  util:[["molo","Tunnels-Timing"],["smoke","Retake A / Long"],["flash","Retake-Flash"],["he","Cat-Damage"]]}
],
de_mirage:[
 {name:"A Execute – Palace & Ramp",side:"T",tags:["Execute","A"],
  roles:["Palace Entry","Palace Support","Ramp Entry","Ramp Trade","Connector-Lurk"],
  steps:["Window früh smoken, damit Mid tot ist.","Smokes auf CT, Jungle und Stairs setzen.","Flash über Palace, Palace-Spieler geht als Erster.","Ramp folgt sofort auf den Flash, Trades laufen.","Post-Plant: Sandwich, Palace und Ramp halten, Lurk auf Connector."],
  util:[["smoke","CT-Spawn"],["smoke","Jungle"],["smoke","Stairs"],["smoke","Window"],["flash","Palace-Flash"]]},
 {name:"B Split – Apps & Short",side:"T",tags:["Split","B"],
  roles:["Apps Entry","Apps Support","Short Entry","Short Support","Mid-Kontrolle"],
  steps:["Window-Smoke früh, Mid-Kontrolle mit einem Spieler.","Molly auf Bench, Smoke auf Market Door.","Drei sammeln Apps, zwei über Short/Catwalk.","Flash von Apps rein, beide Seiten gleichzeitig.","Post-Plant: Bench, Market und Van abdecken."],
  util:[["smoke","Window"],["smoke","Market Door"],["molo","Bench"],["flash","Apps-Entry"],["flash","Short-Support"]]},
 {name:"Mid to A – Fast",side:"T",tags:["Fast","A","Mid"],
  roles:["Connector Entry","Top Mid","Cat Support","Ramp Fake","Lurk B"],
  steps:["Sofort Window und Top-Connector smoken.","Zwei nehmen Cat schnell, Ramp macht Lärm als Fake.","Über Connector rein, Jungle und CT smoken.","Ramp schwingt nach, sobald Site offen ist.","Lurk hält B-Apps gegen Rotation."],
  util:[["smoke","Window"],["smoke","Top Connector"],["smoke","Jungle"],["smoke","CT-Spawn"],["flash","Connector-Entry"]]},
 {name:"Default 2-1-2",side:"CT",tags:["Default","Setup"],
  roles:["A Ramp / Palace","A Site / Jungle","Mid AWP","B Market","B Site"],
  steps:["Mid-AWP hält Top Mid, Window-Kontrolle ist Priorität.","A-Spieler spielt Tetris passiv, Jungle traded.","B-Market spielt aggressiv gegen Apps-Timing.","Bei Mid-Verlust sofort auf Connector-Smoke gehen.","Retake B immer über Market und Kitchen zusammen."],
  util:[["smoke","Connector (Retake)"],["molo","Apps-Timing"],["flash","Palace-Flash"],["he","Cat-Damage"]]}
],
de_inferno:[
 {name:"Banana Control → B Execute",side:"T",tags:["Execute","B"],
  roles:["Banana Entry","Banana Support","Molly-Support","Flash-Support","Mid / Second Mid Lurk"],
  steps:["Sofort Molly auf Car und Coffin, Banana freimachen.","Smoke auf CT und New Box, Banana bis oben halten.","Molly ins Fass / Dark, dann Pop-Flash über die Wand.","Entry über Banana, sofort Site aufteilen: Coffin, New Box, Dark.","Lurk hält Second Mid gegen Rotation."],
  util:[["molo","Car"],["molo","Coffin"],["smoke","CT-Spawn"],["smoke","New Box"],["flash","Entry-Flash über die Wand"]]},
 {name:"A Execute – Apps & Long",side:"T",tags:["Execute","A"],
  roles:["Apps Entry","Apps Support","Long Entry","Long Support","Banana-Lurk"],
  steps:["Banana kurz anspielen, dann alle Richtung Mid drehen.","Smokes auf CT, Library und Short setzen.","Molly auf Graveyard und Pit-Flash werfen.","Apps und Long gleichzeitig rein, Trades zwingend.","Post-Plant: Pit, Graveyard und Truck abdecken."],
  util:[["smoke","CT-Spawn"],["smoke","Library"],["smoke","Short / Balcony"],["molo","Graveyard"],["flash","Pit-Flash"]]},
 {name:"Second Mid Split – A",side:"T",tags:["Split","A","Mid"],
  roles:["Second Mid 1","Second Mid 2","Apps Entry","Apps Support","Banana-Fake"],
  steps:["Ein Spieler macht Lärm auf Banana, Molly auf Car.","Zwei nehmen Second Mid ruhig, Arch smoken.","Library und CT smoken, Short mit Flash freimachen.","Apps und Second Mid zeitgleich rein.","Post-Plant: Boiler und Long im Blick behalten."],
  util:[["smoke","Arch / Second Mid"],["smoke","Library"],["smoke","CT-Spawn"],["molo","Car"],["flash","Short-Flash"]]},
 {name:"Aggro Banana Setup",side:"CT",tags:["Default","Setup"],
  roles:["Banana Aggro","B Site / Fountain","Mid AWP","A Short","A Site / Pit"],
  steps:["Banana-Spieler nimmt jede Runde Info mit Flash, fällt danach zurück.","Mid hält Second Mid, wirft Molly auf Banana-Timing.","A-Short spielt hinter Boiler, nie im Open.","B-Site steht Dark oder Fountain, nie beides gleich.","Retake B nur zusammen mit Smoke aus CT."],
  util:[["molo","Banana-Timing"],["smoke","Retake B / CT"],["flash","Banana-Info-Flash"],["he","Banana-Damage"]]}
],
de_nuke:[
 {name:"Outside → B Fake, A Hit",side:"T",tags:["Fake","A"],
  roles:["Outside Entry","Outside Support","Squeaky","Hut Entry","Lurk Lobby"],
  steps:["Drei gehen Outside, Silo und Garage smoken.","Lärm machen, Molly in Secret werfen (B-Fake).","Squeaky und Hut nehmen leise Position auf A.","Auf Call: Heaven smoken, Flash rein, A-Site hitten.","Outside rotiert über Secret als Post-Plant-Sandwich."],
  util:[["smoke","Silo"],["smoke","Garage"],["smoke","Heaven"],["molo","Secret"],["flash","A-Site Entry"]]},
 {name:"A Split – Squeaky & Hut",side:"T",tags:["Split","A"],
  roles:["Squeaky Entry","Squeaky Support","Hut Entry","Hut Support","Ramp-Kontrolle"],
  steps:["Ramp-Spieler smoket Heaven und hält Ramp-Kontrolle.","Molly auf Boxen und Mini, Flash über Hut.","Squeaky und Hut zeitgleich rein, Trade sofort.","Ramp folgt als Vierter, Bombe auf Mini oder Rafters.","Post-Plant: Heaven, Ramp und Hut abdecken."],
  util:[["smoke","Heaven"],["molo","Boxen / Mini"],["flash","Hut-Entry"],["flash","Squeaky-Flash"],["smoke","Ramp"]]},
 {name:"Ramp Force → B",side:"T",tags:["Execute","B"],
  roles:["Ramp Entry","Ramp Support","Ramp Trade","Vents","Lurk Outside"],
  steps:["Vents-Spieler geht früh und leise, hält Info.","Ramp mit Smokes auf Heaven und Ramp-Ende drücken.","Molly in Double Doors, dann Flash rein.","Vents öffnet zeitgleich, B-Site von zwei Seiten.","Outside-Lurk hält Rotation von Garage."],
  util:[["smoke","Heaven"],["smoke","Ramp-Ende"],["molo","Double Doors"],["flash","Ramp-Entry"]]},
 {name:"Standard 2-1-2",side:"CT",tags:["Default","Setup"],
  roles:["Outside AWP","Garage / Secret","Heaven","A Site","B Site / Vents"],
  steps:["Outside-AWP hält Silo-Winkel, fällt bei Druck in Garage.","Heaven deckt A und kann sofort auf Ramp mollen.","A-Site steht wechselnd Rafters oder Mini.","B hält Vents mit Sound, Double Doors mit Molly.","Retake A immer über Heaven und Squeaky gleichzeitig."],
  util:[["molo","Ramp-Timing"],["smoke","Retake A"],["flash","Heaven-Flash"],["he","Vents-Damage"]]}
],
de_ancient:[
 {name:"A Execute – Donut & Main",side:"T",tags:["Execute","A"],
  roles:["Main Entry","Main Support","Donut Entry","Donut Support","Mid-Lurk"],
  steps:["Mid-Kontrolle mit einem Spieler, Temple smoken.","Smokes auf CT und Elbow, Molly in den Donut.","Flash über Main, Entry geht rein.","Donut-Seite schwingt zeitgleich, Cross-Fire vermeiden.","Post-Plant: Temple, Elbow und Heaven abdecken."],
  util:[["smoke","CT-Spawn"],["smoke","Elbow"],["smoke","Temple"],["molo","Donut"],["flash","Main-Entry"]]},
 {name:"B Split – Cave & Main",side:"T",tags:["Split","B"],
  roles:["Cave Entry","Cave Support","B-Main Entry","B-Main Support","A-Fake"],
  steps:["Ein Spieler macht Lärm auf A-Main (Fake).","Mid nehmen, Cave leise besetzen.","Smoke auf Ramp und CT, Molly hinter Boxen.","Flash von Cave, beide Seiten gleichzeitig rein.","Post-Plant: Ramp und Cave halten, A-Fake rotiert."],
  util:[["smoke","Ramp"],["smoke","CT-Spawn"],["molo","Hinter Boxen"],["flash","Cave-Entry"],["flash","Main-Flash"]]},
 {name:"Mid Control Setup",side:"CT",tags:["Default","Setup"],
  roles:["A Main","A Site / Temple","Mid AWP","B Ramp","B Site / Cave"],
  steps:["Mid-AWP hält Doppeltür, Support wirft Flash bei Push.","A-Main spielt hinter Ecke, nie Open-Peek.","B-Ramp mollt Cave-Timing früh.","Bei Mid-Verlust sofort Smoke auf Doppeltür.","Retake B immer über Ramp und Heaven zusammen."],
  util:[["molo","Cave-Timing"],["smoke","Doppeltür"],["flash","Mid-Flash"],["he","Main-Damage"]]}
],
de_anubis:[
 {name:"A Execute – Palace & Main",side:"T",tags:["Execute","A"],
  roles:["Main Entry","Main Support","Palace Entry","Palace Support","Mid-Lurk"],
  steps:["Mid und Water anspielen, Info sammeln.","Smokes auf Connector und Heaven, Molly in die Ecke.","Flash über Palace, Palace geht als Erster.","Main folgt sofort, Site aufteilen.","Post-Plant: Connector und Heaven abdecken."],
  util:[["smoke","Connector"],["smoke","Heaven"],["molo","Site-Ecke"],["flash","Palace-Entry"],["flash","Main-Flash"]]},
 {name:"B Split – Water & Connector",side:"T",tags:["Split","B"],
  roles:["Water Entry","Water Support","B-Main Entry","B-Main Support","A-Fake"],
  steps:["A-Main kurz anspielen, dann Richtung Mid drehen.","Mid-Kontrolle, Connector smoken.","Molly auf Boxen, Smoke auf CT.","Water und B-Main zeitgleich rein, Trades laufen.","Post-Plant: Connector und Bridge halten."],
  util:[["smoke","Connector"],["smoke","CT-Spawn"],["molo","Boxen"],["flash","Water-Entry"],["flash","B-Main Flash"]]},
 {name:"Mid Priority Setup",side:"CT",tags:["Default","Setup"],
  roles:["A Main","A Site","Mid AWP","Water / Connector","B Site"],
  steps:["Mid-AWP hält Bridge, Connector-Spieler traded.","A-Main spielt passiv, gibt kein Free-Trade.","Water wird jede Runde mit Molly oder Flash kontrolliert.","Bei Mid-Verlust beide Sites eng stellen, kein Solo-Peek.","Retake immer mit Smoke auf Connector."],
  util:[["molo","Water-Timing"],["smoke","Connector (Retake)"],["flash","Bridge-Flash"],["he","Main-Damage"]]}
],
de_cache:[
 {name:"A Execute – Highway & Truck",side:"T",tags:["Execute","A"],
  roles:["Main Entry","Main Support","Highway Entry","Highway Support","Mid-Lurk"],
  steps:["Mid-Spieler nimmt Info und hält Boost-Winkel.","Smokes auf CT und Quad, Molly auf Site / Ninja.","Flash über Truck, Highway geht rein.","A-Main schwingt zeitgleich, Trade auf Quad.","Post-Plant: Quad, Truck und Heaven abdecken."],
  util:[["smoke","CT-Spawn"],["smoke","Quad"],["molo","Site / Ninja"],["flash","Truck-Flash"],["flash","Main-Entry"]]},
 {name:"B Rush – Checkers",side:"T",tags:["Rush","B"],
  roles:["Entry Checkers","Trade","Molly-Support","Flash-Support","Mid-Fake"],
  steps:["Mid-Spieler schießt kurz Mid an und wirft Flash (Fake).","Vier sammeln in B-Halls, Heaven smoken.","Molly hinter Boxen, Flash über Checkers.","Alle vier zusammen raus, Site sofort aufteilen.","Post-Plant: Heaven, Halls und Site-Ecke halten."],
  util:[["smoke","Heaven"],["molo","Hinter Boxen"],["flash","Checkers-Flash"],["flash","Mid-Fake"]]},
 {name:"Mid → B Split",side:"T",tags:["Split","B","Mid"],
  roles:["Mid AWP","Mid Support","Halls Entry","Halls Support","A-Fake"],
  steps:["Mid mit Smoke auf Boost und CT freimachen.","Zwei halten Mid und öffnen Richtung Vents.","Halls sammelt und wartet auf Call.","Heaven smoken, Flash von beiden Seiten, split rein.","Post-Plant: Vents und Halls kontrollieren."],
  util:[["smoke","Boost"],["smoke","CT-Spawn"],["smoke","Heaven"],["flash","Halls-Entry"],["molo","Site-Ecke"]]},
 {name:"Default 1-2-2 mit Mid AWP",side:"CT",tags:["Default","Setup"],
  roles:["A Main","A Site / Quad","Mid AWP","B Halls","B Site / Heaven"],
  steps:["Mid-AWP hält Boost-Winkel, Support gibt Flash.","A-Main spielt hinter Highway-Ecke, kein Open-Peek.","B-Halls mollt Halls-Timing früh und fällt zurück.","Heaven ist Standard-Position für den Retake.","Rotation nur auf klaren Call, nie auf Sound allein."],
  util:[["molo","Halls-Timing"],["smoke","Retake B"],["flash","Mid-Flash"],["he","Main-Damage"]]}
]
};
